namespace DoAn
{
    partial class Information
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Information));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel0 = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panel3 = new System.Windows.Forms.Panel();
            this.change1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.EmailC = new Bunifu.UI.WinForms.BunifuTextBox();
            this.phoneC = new Bunifu.UI.WinForms.BunifuTextBox();
            this.adressC = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nameC = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.email = new System.Windows.Forms.Label();
            this.phone = new System.Windows.Forms.Label();
            this.adress = new System.Windows.Forms.Label();
            this.name = new System.Windows.Forms.Label();
            this.change = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.edit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.panel4 = new System.Windows.Forms.Panel();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.label1 = new System.Windows.Forms.Label();
            this.panel0.SuspendLayout();
            this.panel2.SuspendLayout();
            this.panel3.SuspendLayout();
            this.panel4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel0
            // 
            this.panel0.Controls.Add(this.panel2);
            this.panel0.Controls.Add(this.panel1);
            this.panel0.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel0.Location = new System.Drawing.Point(0, 0);
            this.panel0.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.panel0.Name = "panel0";
            this.panel0.Size = new System.Drawing.Size(1138, 771);
            this.panel0.TabIndex = 0;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.panel3);
            this.panel2.Controls.Add(this.panel4);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel2.Location = new System.Drawing.Point(0, 79);
            this.panel2.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(1138, 692);
            this.panel2.TabIndex = 1;
            // 
            // panel3
            // 
            this.panel3.BackColor = System.Drawing.Color.Transparent;
            this.panel3.Controls.Add(this.change1);
            this.panel3.Controls.Add(this.EmailC);
            this.panel3.Controls.Add(this.phoneC);
            this.panel3.Controls.Add(this.adressC);
            this.panel3.Controls.Add(this.nameC);
            this.panel3.Controls.Add(this.bunifuTextBox1);
            this.panel3.Controls.Add(this.email);
            this.panel3.Controls.Add(this.phone);
            this.panel3.Controls.Add(this.adress);
            this.panel3.Controls.Add(this.name);
            this.panel3.Controls.Add(this.change);
            this.panel3.Controls.Add(this.edit);
            this.panel3.Controls.Add(this.label6);
            this.panel3.Controls.Add(this.label5);
            this.panel3.Controls.Add(this.label4);
            this.panel3.Controls.Add(this.label3);
            this.panel3.Controls.Add(this.label2);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Right;
            this.panel3.Location = new System.Drawing.Point(223, 0);
            this.panel3.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(915, 692);
            this.panel3.TabIndex = 1;
            // 
            // change1
            // 
            this.change1.AllowAnimations = true;
            this.change1.AllowMouseEffects = true;
            this.change1.AllowToggling = false;
            this.change1.AnimationSpeed = 200;
            this.change1.AutoGenerateColors = false;
            this.change1.AutoRoundBorders = false;
            this.change1.AutoSizeLeftIcon = true;
            this.change1.AutoSizeRightIcon = true;
            this.change1.BackColor = System.Drawing.Color.Transparent;
            this.change1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.change1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("change1.BackgroundImage")));
            this.change1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.change1.ButtonText = "Change";
            this.change1.ButtonTextMarginLeft = 0;
            this.change1.ColorContrastOnClick = 45;
            this.change1.ColorContrastOnHover = 45;
            this.change1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.change1.CustomizableEdges = borderEdges1;
            this.change1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.change1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.change1.DisabledFillColor = System.Drawing.Color.Empty;
            this.change1.DisabledForecolor = System.Drawing.Color.Empty;
            this.change1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.change1.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.change1.ForeColor = System.Drawing.Color.White;
            this.change1.IconLeft = null;
            this.change1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.change1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.change1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.change1.IconMarginLeft = 11;
            this.change1.IconPadding = 10;
            this.change1.IconRight = null;
            this.change1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.change1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.change1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.change1.IconSize = 25;
            this.change1.IdleBorderColor = System.Drawing.Color.Empty;
            this.change1.IdleBorderRadius = 0;
            this.change1.IdleBorderThickness = 0;
            this.change1.IdleFillColor = System.Drawing.Color.Empty;
            this.change1.IdleIconLeftImage = null;
            this.change1.IdleIconRightImage = null;
            this.change1.IndicateFocus = false;
            this.change1.Location = new System.Drawing.Point(348, 415);
            this.change1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.change1.Name = "change1";
            this.change1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.change1.OnDisabledState.BorderRadius = 1;
            this.change1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.change1.OnDisabledState.BorderThickness = 1;
            this.change1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.change1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.change1.OnDisabledState.IconLeftImage = null;
            this.change1.OnDisabledState.IconRightImage = null;
            this.change1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.change1.onHoverState.BorderRadius = 1;
            this.change1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.change1.onHoverState.BorderThickness = 1;
            this.change1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.change1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.change1.onHoverState.IconLeftImage = null;
            this.change1.onHoverState.IconRightImage = null;
            this.change1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.change1.OnIdleState.BorderRadius = 1;
            this.change1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.change1.OnIdleState.BorderThickness = 1;
            this.change1.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.change1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.change1.OnIdleState.IconLeftImage = null;
            this.change1.OnIdleState.IconRightImage = null;
            this.change1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.change1.OnPressedState.BorderRadius = 1;
            this.change1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.change1.OnPressedState.BorderThickness = 1;
            this.change1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.change1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.change1.OnPressedState.IconLeftImage = null;
            this.change1.OnPressedState.IconRightImage = null;
            this.change1.Size = new System.Drawing.Size(116, 54);
            this.change1.TabIndex = 16;
            this.change1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.change1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.change1.TextMarginLeft = 0;
            this.change1.TextPadding = new System.Windows.Forms.Padding(0);
            this.change1.UseDefaultRadiusAndThickness = true;
            this.change1.Visible = false;
            // 
            // EmailC
            // 
            this.EmailC.AcceptsReturn = false;
            this.EmailC.AcceptsTab = false;
            this.EmailC.AnimationSpeed = 200;
            this.EmailC.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.EmailC.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.EmailC.AutoSizeHeight = true;
            this.EmailC.BackColor = System.Drawing.Color.Transparent;
            this.EmailC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EmailC.BackgroundImage")));
            this.EmailC.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.EmailC.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EmailC.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.EmailC.BorderColorIdle = System.Drawing.Color.Silver;
            this.EmailC.BorderRadius = 1;
            this.EmailC.BorderThickness = 1;
            this.EmailC.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.EmailC.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailC.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.EmailC.DefaultText = "";
            this.EmailC.FillColor = System.Drawing.Color.White;
            this.EmailC.HideSelection = true;
            this.EmailC.IconLeft = null;
            this.EmailC.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailC.IconPadding = 10;
            this.EmailC.IconRight = null;
            this.EmailC.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailC.Lines = new string[0];
            this.EmailC.Location = new System.Drawing.Point(205, 249);
            this.EmailC.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.EmailC.MaxLength = 32767;
            this.EmailC.MinimumSize = new System.Drawing.Size(1, 1);
            this.EmailC.Modified = false;
            this.EmailC.Multiline = false;
            this.EmailC.Name = "EmailC";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailC.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.EmailC.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailC.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailC.OnIdleState = stateProperties4;
            this.EmailC.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.EmailC.PasswordChar = '\0';
            this.EmailC.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.EmailC.PlaceholderText = "Enter text";
            this.EmailC.ReadOnly = false;
            this.EmailC.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.EmailC.SelectedText = "";
            this.EmailC.SelectionLength = 0;
            this.EmailC.SelectionStart = 0;
            this.EmailC.ShortcutsEnabled = true;
            this.EmailC.Size = new System.Drawing.Size(450, 46);
            this.EmailC.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.EmailC.TabIndex = 15;
            this.EmailC.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.EmailC.TextMarginBottom = 0;
            this.EmailC.TextMarginLeft = 3;
            this.EmailC.TextMarginTop = 1;
            this.EmailC.TextPlaceholder = "Enter text";
            this.EmailC.UseSystemPasswordChar = false;
            this.EmailC.Visible = false;
            this.EmailC.WordWrap = true;
            // 
            // phoneC
            // 
            this.phoneC.AcceptsReturn = false;
            this.phoneC.AcceptsTab = false;
            this.phoneC.AnimationSpeed = 200;
            this.phoneC.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phoneC.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phoneC.AutoSizeHeight = true;
            this.phoneC.BackColor = System.Drawing.Color.Transparent;
            this.phoneC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phoneC.BackgroundImage")));
            this.phoneC.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.phoneC.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phoneC.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.phoneC.BorderColorIdle = System.Drawing.Color.Silver;
            this.phoneC.BorderRadius = 1;
            this.phoneC.BorderThickness = 1;
            this.phoneC.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phoneC.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phoneC.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.phoneC.DefaultText = "";
            this.phoneC.FillColor = System.Drawing.Color.White;
            this.phoneC.HideSelection = true;
            this.phoneC.IconLeft = null;
            this.phoneC.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phoneC.IconPadding = 10;
            this.phoneC.IconRight = null;
            this.phoneC.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phoneC.Lines = new string[0];
            this.phoneC.Location = new System.Drawing.Point(205, 188);
            this.phoneC.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.phoneC.MaxLength = 32767;
            this.phoneC.MinimumSize = new System.Drawing.Size(1, 1);
            this.phoneC.Modified = false;
            this.phoneC.Multiline = false;
            this.phoneC.Name = "phoneC";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phoneC.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phoneC.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phoneC.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phoneC.OnIdleState = stateProperties8;
            this.phoneC.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.phoneC.PasswordChar = '\0';
            this.phoneC.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phoneC.PlaceholderText = "Enter text";
            this.phoneC.ReadOnly = false;
            this.phoneC.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phoneC.SelectedText = "";
            this.phoneC.SelectionLength = 0;
            this.phoneC.SelectionStart = 0;
            this.phoneC.ShortcutsEnabled = true;
            this.phoneC.Size = new System.Drawing.Size(450, 46);
            this.phoneC.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phoneC.TabIndex = 14;
            this.phoneC.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phoneC.TextMarginBottom = 0;
            this.phoneC.TextMarginLeft = 3;
            this.phoneC.TextMarginTop = 1;
            this.phoneC.TextPlaceholder = "Enter text";
            this.phoneC.UseSystemPasswordChar = false;
            this.phoneC.Visible = false;
            this.phoneC.WordWrap = true;
            // 
            // adressC
            // 
            this.adressC.AcceptsReturn = false;
            this.adressC.AcceptsTab = false;
            this.adressC.AnimationSpeed = 200;
            this.adressC.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.adressC.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.adressC.AutoSizeHeight = true;
            this.adressC.BackColor = System.Drawing.Color.Transparent;
            this.adressC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("adressC.BackgroundImage")));
            this.adressC.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.adressC.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.adressC.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.adressC.BorderColorIdle = System.Drawing.Color.Silver;
            this.adressC.BorderRadius = 1;
            this.adressC.BorderThickness = 1;
            this.adressC.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.adressC.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.adressC.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.adressC.DefaultText = "";
            this.adressC.FillColor = System.Drawing.Color.White;
            this.adressC.HideSelection = true;
            this.adressC.IconLeft = null;
            this.adressC.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.adressC.IconPadding = 10;
            this.adressC.IconRight = null;
            this.adressC.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.adressC.Lines = new string[0];
            this.adressC.Location = new System.Drawing.Point(205, 122);
            this.adressC.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.adressC.MaxLength = 32767;
            this.adressC.MinimumSize = new System.Drawing.Size(1, 1);
            this.adressC.Modified = false;
            this.adressC.Multiline = false;
            this.adressC.Name = "adressC";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adressC.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.adressC.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adressC.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adressC.OnIdleState = stateProperties12;
            this.adressC.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.adressC.PasswordChar = '\0';
            this.adressC.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.adressC.PlaceholderText = "Enter text";
            this.adressC.ReadOnly = false;
            this.adressC.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.adressC.SelectedText = "";
            this.adressC.SelectionLength = 0;
            this.adressC.SelectionStart = 0;
            this.adressC.ShortcutsEnabled = true;
            this.adressC.Size = new System.Drawing.Size(450, 46);
            this.adressC.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.adressC.TabIndex = 13;
            this.adressC.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.adressC.TextMarginBottom = 0;
            this.adressC.TextMarginLeft = 3;
            this.adressC.TextMarginTop = 1;
            this.adressC.TextPlaceholder = "Enter text";
            this.adressC.UseSystemPasswordChar = false;
            this.adressC.Visible = false;
            this.adressC.WordWrap = true;
            // 
            // nameC
            // 
            this.nameC.AcceptsReturn = false;
            this.nameC.AcceptsTab = false;
            this.nameC.AnimationSpeed = 200;
            this.nameC.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nameC.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nameC.AutoSizeHeight = true;
            this.nameC.BackColor = System.Drawing.Color.Transparent;
            this.nameC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nameC.BackgroundImage")));
            this.nameC.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nameC.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nameC.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nameC.BorderColorIdle = System.Drawing.Color.Silver;
            this.nameC.BorderRadius = 1;
            this.nameC.BorderThickness = 1;
            this.nameC.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nameC.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nameC.DefaultFont = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nameC.DefaultText = "";
            this.nameC.FillColor = System.Drawing.Color.White;
            this.nameC.HideSelection = true;
            this.nameC.IconLeft = null;
            this.nameC.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameC.IconPadding = 10;
            this.nameC.IconRight = null;
            this.nameC.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameC.Lines = new string[0];
            this.nameC.Location = new System.Drawing.Point(205, 51);
            this.nameC.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.nameC.MaxLength = 32767;
            this.nameC.MinimumSize = new System.Drawing.Size(1, 1);
            this.nameC.Modified = false;
            this.nameC.Multiline = false;
            this.nameC.Name = "nameC";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameC.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nameC.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameC.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameC.OnIdleState = stateProperties16;
            this.nameC.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.nameC.PasswordChar = '\0';
            this.nameC.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nameC.PlaceholderText = "Enter text";
            this.nameC.ReadOnly = false;
            this.nameC.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nameC.SelectedText = "";
            this.nameC.SelectionLength = 0;
            this.nameC.SelectionStart = 0;
            this.nameC.ShortcutsEnabled = true;
            this.nameC.Size = new System.Drawing.Size(450, 46);
            this.nameC.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nameC.TabIndex = 12;
            this.nameC.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nameC.TextMarginBottom = 0;
            this.nameC.TextMarginLeft = 3;
            this.nameC.TextMarginTop = 1;
            this.nameC.TextPlaceholder = "Enter text";
            this.nameC.UseSystemPasswordChar = false;
            this.nameC.Visible = false;
            this.nameC.WordWrap = true;
            this.nameC.TextChanged += new System.EventHandler(this.nameC_TextChanged);
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.AutoSizeHeight = true;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BorderRadius = 1;
            this.bunifuTextBox1.BorderThickness = 0;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox1.DefaultText = "password2";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuTextBox1.HideSelection = false;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[] {
        "password2"};
            this.bunifuTextBox1.Location = new System.Drawing.Point(251, 316);
            this.bunifuTextBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties17.BorderColor = System.Drawing.Color.Transparent;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Transparent;
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Transparent;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Transparent;
            stateProperties20.FillColor = System.Drawing.Color.WhiteSmoke;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties20;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuTextBox1.PasswordChar = '●';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox1.PlaceholderText = "Enter text";
            this.bunifuTextBox1.ReadOnly = true;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 9;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(281, 39);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox1.TabIndex = 11;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 1;
            this.bunifuTextBox1.TextPlaceholder = "Enter text";
            this.bunifuTextBox1.UseSystemPasswordChar = true;
            this.bunifuTextBox1.WordWrap = true;
            // 
            // email
            // 
            this.email.AutoSize = true;
            this.email.Font = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.email.Location = new System.Drawing.Point(200, 262);
            this.email.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.email.Name = "email";
            this.email.Size = new System.Drawing.Size(230, 29);
            this.email.TabIndex = 10;
            this.email.Text = "thangnd@gmail.com";
            // 
            // phone
            // 
            this.phone.AutoSize = true;
            this.phone.Font = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.phone.Location = new System.Drawing.Point(200, 201);
            this.phone.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.phone.Name = "phone";
            this.phone.Size = new System.Drawing.Size(155, 29);
            this.phone.TabIndex = 9;
            this.phone.Text = "0123 456 789";
            // 
            // adress
            // 
            this.adress.AutoSize = true;
            this.adress.Font = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.adress.Location = new System.Drawing.Point(200, 135);
            this.adress.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.adress.Name = "adress";
            this.adress.Size = new System.Drawing.Size(294, 29);
            this.adress.TabIndex = 8;
            this.adress.Text = "Ho Chi Minh city, Viet Nam";
            // 
            // name
            // 
            this.name.AutoSize = true;
            this.name.Font = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.name.Location = new System.Drawing.Point(200, 64);
            this.name.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.name.Name = "name";
            this.name.Size = new System.Drawing.Size(211, 29);
            this.name.TabIndex = 7;
            this.name.Text = "Nguyen Duc Thang";
            // 
            // change
            // 
            this.change.AllowAnimations = true;
            this.change.AllowMouseEffects = true;
            this.change.AllowToggling = false;
            this.change.AnimationSpeed = 200;
            this.change.AutoGenerateColors = false;
            this.change.AutoRoundBorders = false;
            this.change.AutoSizeLeftIcon = true;
            this.change.AutoSizeRightIcon = true;
            this.change.BackColor = System.Drawing.Color.Transparent;
            this.change.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.change.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("change.BackgroundImage")));
            this.change.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.change.ButtonText = "Change";
            this.change.ButtonTextMarginLeft = 0;
            this.change.ColorContrastOnClick = 45;
            this.change.ColorContrastOnHover = 45;
            this.change.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.change.CustomizableEdges = borderEdges2;
            this.change.DialogResult = System.Windows.Forms.DialogResult.None;
            this.change.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.change.DisabledFillColor = System.Drawing.Color.Empty;
            this.change.DisabledForecolor = System.Drawing.Color.Empty;
            this.change.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.change.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.change.ForeColor = System.Drawing.Color.White;
            this.change.IconLeft = null;
            this.change.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.change.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.change.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.change.IconMarginLeft = 11;
            this.change.IconPadding = 10;
            this.change.IconRight = null;
            this.change.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.change.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.change.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.change.IconSize = 25;
            this.change.IdleBorderColor = System.Drawing.Color.Empty;
            this.change.IdleBorderRadius = 0;
            this.change.IdleBorderThickness = 0;
            this.change.IdleFillColor = System.Drawing.Color.Empty;
            this.change.IdleIconLeftImage = null;
            this.change.IdleIconRightImage = null;
            this.change.IndicateFocus = false;
            this.change.Location = new System.Drawing.Point(348, 415);
            this.change.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.change.Name = "change";
            this.change.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.change.OnDisabledState.BorderRadius = 1;
            this.change.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.change.OnDisabledState.BorderThickness = 1;
            this.change.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.change.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.change.OnDisabledState.IconLeftImage = null;
            this.change.OnDisabledState.IconRightImage = null;
            this.change.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.change.onHoverState.BorderRadius = 1;
            this.change.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.change.onHoverState.BorderThickness = 1;
            this.change.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.change.onHoverState.ForeColor = System.Drawing.Color.White;
            this.change.onHoverState.IconLeftImage = null;
            this.change.onHoverState.IconRightImage = null;
            this.change.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.change.OnIdleState.BorderRadius = 1;
            this.change.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.change.OnIdleState.BorderThickness = 1;
            this.change.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.change.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.change.OnIdleState.IconLeftImage = null;
            this.change.OnIdleState.IconRightImage = null;
            this.change.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.change.OnPressedState.BorderRadius = 1;
            this.change.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.change.OnPressedState.BorderThickness = 1;
            this.change.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.change.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.change.OnPressedState.IconLeftImage = null;
            this.change.OnPressedState.IconRightImage = null;
            this.change.Size = new System.Drawing.Size(116, 54);
            this.change.TabIndex = 6;
            this.change.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.change.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.change.TextMarginLeft = 0;
            this.change.TextPadding = new System.Windows.Forms.Padding(0);
            this.change.UseDefaultRadiusAndThickness = true;
            this.change.Visible = false;
            this.change.Click += new System.EventHandler(this.change_Click);
            // 
            // edit
            // 
            this.edit.AllowAnimations = true;
            this.edit.AllowMouseEffects = true;
            this.edit.AllowToggling = false;
            this.edit.AnimationSpeed = 200;
            this.edit.AutoGenerateColors = false;
            this.edit.AutoRoundBorders = false;
            this.edit.AutoSizeLeftIcon = true;
            this.edit.AutoSizeRightIcon = true;
            this.edit.BackColor = System.Drawing.Color.Transparent;
            this.edit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.edit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("edit.BackgroundImage")));
            this.edit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.edit.ButtonText = "Edit";
            this.edit.ButtonTextMarginLeft = 0;
            this.edit.ColorContrastOnClick = 45;
            this.edit.ColorContrastOnHover = 45;
            this.edit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.edit.CustomizableEdges = borderEdges3;
            this.edit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.edit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.edit.DisabledFillColor = System.Drawing.Color.Empty;
            this.edit.DisabledForecolor = System.Drawing.Color.Empty;
            this.edit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.edit.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.edit.ForeColor = System.Drawing.Color.White;
            this.edit.IconLeft = null;
            this.edit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.edit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.edit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.edit.IconMarginLeft = 11;
            this.edit.IconPadding = 10;
            this.edit.IconRight = null;
            this.edit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.edit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.edit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.edit.IconSize = 25;
            this.edit.IdleBorderColor = System.Drawing.Color.Empty;
            this.edit.IdleBorderRadius = 0;
            this.edit.IdleBorderThickness = 0;
            this.edit.IdleFillColor = System.Drawing.Color.Empty;
            this.edit.IdleIconLeftImage = null;
            this.edit.IdleIconRightImage = null;
            this.edit.IndicateFocus = false;
            this.edit.Location = new System.Drawing.Point(348, 415);
            this.edit.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.edit.Name = "edit";
            this.edit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.edit.OnDisabledState.BorderRadius = 1;
            this.edit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.edit.OnDisabledState.BorderThickness = 1;
            this.edit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.edit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.edit.OnDisabledState.IconLeftImage = null;
            this.edit.OnDisabledState.IconRightImage = null;
            this.edit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.edit.onHoverState.BorderRadius = 1;
            this.edit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.edit.onHoverState.BorderThickness = 1;
            this.edit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.edit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.edit.onHoverState.IconLeftImage = null;
            this.edit.onHoverState.IconRightImage = null;
            this.edit.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.edit.OnIdleState.BorderRadius = 1;
            this.edit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.edit.OnIdleState.BorderThickness = 1;
            this.edit.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.edit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.edit.OnIdleState.IconLeftImage = null;
            this.edit.OnIdleState.IconRightImage = null;
            this.edit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.edit.OnPressedState.BorderRadius = 1;
            this.edit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.edit.OnPressedState.BorderThickness = 1;
            this.edit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.edit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.edit.OnPressedState.IconLeftImage = null;
            this.edit.OnPressedState.IconRightImage = null;
            this.edit.Size = new System.Drawing.Size(116, 54);
            this.edit.TabIndex = 5;
            this.edit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.edit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.edit.TextMarginLeft = 0;
            this.edit.TextPadding = new System.Windows.Forms.Padding(0);
            this.edit.UseDefaultRadiusAndThickness = true;
            this.edit.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(101, 327);
            this.label6.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(138, 29);
            this.label6.TabIndex = 4;
            this.label6.Text = "Password 2:";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(101, 259);
            this.label5.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(75, 29);
            this.label5.TabIndex = 3;
            this.label5.Text = "Email:";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(101, 198);
            this.label4.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(84, 29);
            this.label4.TabIndex = 2;
            this.label4.Text = "Phone:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(101, 132);
            this.label3.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(89, 29);
            this.label3.TabIndex = 1;
            this.label3.Text = "Adress:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Tai Le", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(101, 62);
            this.label2.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(80, 29);
            this.label2.TabIndex = 0;
            this.label2.Text = "Name:";
            // 
            // panel4
            // 
            this.panel4.Controls.Add(this.bunifuButton2);
            this.panel4.Controls.Add(this.bunifuButton1);
            this.panel4.Controls.Add(this.bunifuPictureBox1);
            this.panel4.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel4.Location = new System.Drawing.Point(0, 0);
            this.panel4.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(218, 692);
            this.panel4.TabIndex = 0;
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Edit";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges4;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeft = null;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRight = null;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleBorderRadius = 0;
            this.bunifuButton2.IdleBorderThickness = 0;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(41, 281);
            this.bunifuButton2.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(116, 28);
            this.bunifuButton2.TabIndex = 8;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton1_Click_1);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Change";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges5;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(34, 288);
            this.bunifuButton1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(115, 32);
            this.bunifuButton1.TabIndex = 7;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Visible = false;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 98;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(2, 51);
            this.bunifuPictureBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(197, 197);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 1;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.label1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1138, 84);
            this.panel1.TabIndex = 0;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Tai Le", 36F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(383, 15);
            this.label1.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(358, 61);
            this.label1.TabIndex = 1;
            this.label1.Text = "YOUR PROFILE";
            // 
            // Information
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1138, 771);
            this.Controls.Add(this.panel0);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.Name = "Information";
            this.Text = "Information";
            this.panel0.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.panel4.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel0;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.Label email;
        private System.Windows.Forms.Label phone;
        private System.Windows.Forms.Label adress;
        private System.Windows.Forms.Label name;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Panel panel4;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Bunifu.UI.WinForms.BunifuTextBox EmailC;
        private Bunifu.UI.WinForms.BunifuTextBox phoneC;
        private Bunifu.UI.WinForms.BunifuTextBox adressC;
        private Bunifu.UI.WinForms.BunifuTextBox nameC;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton change;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton edit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton change1;
    }
}